# Generated by Django 4.2.1 on 2023-06-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
